### ISSUE TITLE
date mask issue

### ISSUE THREAD

**Issue by Maks-Yaremenko** [JsDaddy/ngx-mask#456]
The issue with Valid Date and Month.

When you entered date and then using arrows return for example to the first pair of numbers (for change days for example). After removing and typing a new number next numbers shifted and make date invalid.

Steps to reproduce:
1. type => 04/05/2020
2. remove first 4 => 00/05/2020
3. after entering 7, for example, you'll get this => 07/00/502

I can get the same result on your demo site.

**Comment by ValeriaKochegarova** [comment]
@Maks-Yaremenko we fixed this,  you can try to use it in the latest version (7.9.6)

**Comment by Maks-Yaremenko** [comment]
I checked it today on your demo, also installed lib yesterday on my demo. Issue reproduced.

**Comment by ValeriaKochegarova** [comment]
@Maks-Yaremenko the version 7.9.6 has not published yet , we will publish today later and you can use it

**Comment by hwong668** [comment]
This issue is back, v8.0.3.  It is reproducible on the demo site as well.
